{
  imports = [
    ./ghostty.nix
    ./git.nix
    ./herdr.nix
    ./hyprshot.nix
    ./ideavim.nix
    ./impurity.nix
    ./jujutsu.nix
    ./neovim.nix
    ./noctalia.nix
    ./starship.nix
    ./tmux.nix
    ./utils.nix
    ./vicinae.nix
    ./zed.nix
    ./zen-browser.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
